services:
  app:
    build: .
    container_name: familiaMogi_front
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - familia_mogi_logs:/var/www/html/storage/logs
    depends_on:
      - db
    restart: "no"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: familia_mogi
      DB_USERNAME: postgres
      DB_PASSWORD: rootpassword123

    ports:
      - "8040:80"
      - "5177:5177"
    command: >
      bash -lc "
      chown -R www-data:www-data storage bootstrap/cache &&
      (npm run dev -- --host 0.0.0.0 --port 5177 &) &&
      apache2-foreground"
    networks:
      default: {}
      shared-network:
        aliases:
          - familia-mogi-api


  db:
    image: postgres:16-alpine
    container_name: familiaMogi_front-db
    ports:
      - "5435:5432"
    restart: "no"
    environment:
      POSTGRES_DB: familia_mogi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
  familia_mogi_logs:

networks:
  shared-network:
    external: true
